import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'



export default function Home() {
  const [appId, setAppId] = useState("")
  const [certificate, setCertificate] = useState("")
  const [channel, setChannel] = useState("")
  const [uid, setUid] = useState("")
  const [token, setToken] = useState("")

  function generate(){
    fetch("/api/agora", {
      method:"post",
      body: JSON.stringify({
        appId,
        certificate,
        channel,
        uid
      })
    })
    .then(response => response.json())
    .then(result => {
      setToken(result.token)
    })
  }
  return (
    <>
      <Head>
        <title>Smarty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <label htmlFor='appId'>AppID</label>
        <input id='appId' type={"text"} onChange={(e)=> {setAppId(e.target.value)}}/>

        <label htmlFor='certificate'>Certificate</label>
        <input id='certificate' type={"text"} onChange={(e)=> {setCertificate(e.target.value)}}/>

        <label htmlFor='channel'>Channel</label>
        <input id='channel' type={"text"} onChange={(e)=> {setChannel(e.target.value)}}/>

        <label htmlFor='uid'>Uid</label>
        <input id='uid' type={"text"} onChange={(e)=> {setUid(e.target.value)}}/>

        <button onClick={generate}>Generate</button>

        {token ? token : "empty"}
      </main>
    </>
  )
}
