import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useState} from 'react'

export default function Message() {
    const [accountSid, setAccountSid] = useState("")
    const [authToken, setAuthToken] = useState("")
    const [twilioPhoneNumber, setTwilioPhoneNumber] = useState("")
    const [userPhoneNumber, setUserPhoneNumber] = useState("")
    const [message, setMessage] = useState("")
    const [result, setResult] = useState("")

    function sendMessage() {
        fetch("/api/message", {
            method: "post",
            body: JSON.stringify({
                accountSid,
                authToken,
                twilioPhoneNumber,
                userPhoneNumber,
                message
            })
        })
            .then(result => {
                setResult(result.status.toString())
            })
    }

    return (
        <>
            <Head>
                <title>Smarty | Message</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <label htmlFor='AccountSid'>AccountSid</label>
                <input id='AccountSid' type={"text"} onChange={(e) => {
                    setAccountSid(e.target.value)
                }}/>

                <label htmlFor='AuthToken'>AuthToken</label>
                <input id='AuthToken' type={"text"} onChange={(e) => {
                    setAuthToken(e.target.value)
                }}/>

                <label htmlFor='TwilioPhoneNumber'>TwilioPhoneNumber</label>
                <input id='TwilioPhoneNumber' type={"text"} onChange={(e) => {
                    setTwilioPhoneNumber(e.target.value)
                }}/>

                <label htmlFor='UserPhoneNumber'>UserPhoneNumber</label>
                <input id='UserPhoneNumber' type={"text"} onChange={(e) => {
                    setUserPhoneNumber(e.target.value)
                }}/>


                <label htmlFor='Message'>Message</label>
                <input id='Message' type={"text"} onChange={(e) => {
                    setMessage(e.target.value)
                }}/>

                <button onClick={sendMessage}>Send Message</button>

                {result}
            </main>
        </>
    )
}
