import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import {atob} from "next/dist/compiled/@edge-runtime/primitives/encoding";



export default function Send() {
    const [username, setUsername] = useState("sayatraykulov")
    const [password, setPassword] = useState("@Sayphon2002")
    const [to, setTo] = useState("+77766079387")
    const [message, setMessage] = useState("Hello")

    function send(){
        fetch("/api/send", {
            method:"post",
            body: JSON.stringify({
                username,
                password,
                to,
                message
            })
        })
            .then(response => response.json())
            .then(result => {
                console.log(result)
            })
    }
    return (
        <>
            <Head>
                <title>Smarty</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <label htmlFor='Username'>Username</label>
                <input id='Username' type={"text"} onChange={(e)=> {setUsername(e.target.value)}} defaultValue={username}/>

                <label htmlFor='Password'>Password</label>
                <input id='Password' type={"text"} onChange={(e)=> {setPassword(e.target.value)}} defaultValue={password}/>

                <label htmlFor='To'>To</label>
                <input id='To' type={"text"} onChange={(e)=> {setTo(e.target.value)}} defaultValue={"+77666079387"}/>

                <label htmlFor='Message'>Message</label>
                <input id='Message' type={"text"} onChange={(e)=> {setMessage(e.target.value)}} defaultValue={"Hello"}/>

                <button onClick={send}>Send</button>

            </main>
        </>
    )
}
